In [1]:
#Tutorial from aiworkbox.com/lessons/multiply-two-matrices-using-tensorflow-matmul
import tensorflow as tf

In [2]:
print(tf.__version__)

1.3.0


In [3]:
#The first matrix will be a TensorFlow tensor shaped 3x3 with min values of 1, max values of 10, and the data type will be int32.
random_int_var = tf.get_variable("random_int_var_1_to_10",
                                     initializer=tf.random_uniform([3, 3],
                                                 minval=1,
                                                 maxval=10,
                                                 dtype=tf.int32))
#We use tf.get_variable and we give it the name random_int_var_1_to_10.
#We assign it to the Python variable random_int_var.

In [4]:
print(random_int_var)

<tf.Variable 'random_int_var_1_to_10:0' shape=(3, 3) dtype=int32_ref>


In [5]:
#The second matrix we create will be a TensorFlow tensor shaped 3x3 with integers 
#ones for every element with the data type of int32.
tf_int_ones = tf.ones(shape=[3,3], dtype="int32")

In [6]:
print(tf_int_ones)

Tensor("ones:0", shape=(3, 3), dtype=int32)


In [9]:
#Now that we’ve created our TensorFlow matrix tensors, it’s time to run the computational graph.
sess = tf.Session()

In [10]:
#initialize all the global variables in the graph, in this case, our two matrices:
sess.run(tf.global_variables_initializer())

In [11]:
print(sess.run(random_int_var))

[[4 2 5]
 [7 4 9]
 [6 3 7]]


In [12]:
#Print second matrix
print(sess.run(tf_int_ones))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [13]:
#do the matrix multiplication using tf.matmul operation.
tf_matrix_multiplication_prod = tf.matmul(random_int_var, tf_int_ones)

In [14]:
print(sess.run(tf_matrix_multiplication_prod))

[[11 11 11]
 [20 20 20]
 [16 16 16]]
